table Weekly_Productions
	lineageTag: c7a83df2-d0ea-4379-8cda-b951fb5bef37

	measure 'Week Number' = ```
			
			VAR Start_Of_Year = DATE(YEAR(SELECTEDVALUE(Weekly_Productions[Date])), 1, 1) 
			VAR DayOfWeek = WEEKDAY(Start_Of_Year, 1) // 1 = Sunday, ..., 7 = Saturday
			RETURN 
			INT((SELECTEDVALUE(Weekly_Productions[Date]) - Start_Of_Year + (DayOfWeek + 1) - 1) / 7) + 1
			
			```
		formatString: 0
		lineageTag: c757c8d2-7ebc-4b5f-941e-b44bfc3165ef

	measure 'Production Change' = ```
			
			VAR CurrentProduction = SUM(Weekly_Productions[Production (Thousand Barrels per Day)])
			VAR PreviousWeekProduction = 
			    CALCULATE(
			        SUM(Weekly_Productions[Production (Thousand Barrels per Day)]), 
			        FILTER(
			            Weekly_Productions,
			            Weekly_Productions[Date] = MAX(Weekly_Productions[Date]) - 7
			        )
			    )
			VAR ChangeValue = CurrentProduction - PreviousWeekProduction
			RETURN 
			    IF(
			        ISBLANK(PreviousWeekProduction),
			        BLANK(),
			        ChangeValue
			    )
			
			```
		formatString: 0
		lineageTag: 752436a2-c4cf-42d9-8af8-53b4f75587a0

	column Date
		dataType: dateTime
		formatString: Short Date
		lineageTag: 6277d098-fb44-44fc-ae19-418477867c0a
		summarizeBy: none
		sourceColumn: Date

		variation Variation
			isDefault
			relationship: 56ca314d-a8f5-4484-8621-110764a27b87
			defaultHierarchy: LocalDateTable_03babbdb-0c71-443f-baa7-e666cfda060f.'Date Hierarchy'

		changedProperty = SortByColumn

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Production (Thousand Barrels per Day)'
		dataType: int64
		formatString: 0
		lineageTag: 3455f092-08c8-4b47-b080-0d8821e723a9
		summarizeBy: sum
		sourceColumn: Production (Thousand Barrels per Day)

		annotation SummarizationSetBy = Automatic

	column Week
		dataType: string
		lineageTag: d42f9d5d-a095-4737-b17f-8c57b0ef6547
		summarizeBy: none
		sourceColumn: Week

		annotation SummarizationSetBy = Automatic

	column WeekNum = ```
			WEEKNUM(Weekly_Productions[Date],21)
			
			```
		dataType: int64
		formatString: 0
		lineageTag: fc97b2d7-573d-4e7e-92fa-829fe3659b04
		summarizeBy: sum
		isDataTypeInferred

		annotation SummarizationSetBy = Automatic

	partition Weekly_Productions = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Ayush\Desktop\Weekly Production 1.xlsx"), null, true),
				    Sheet1_Sheet = Source{[Item="Sheet1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Sheet1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Date", type date}, {"Production (Thousand Barrels per Day)", Int64.Type}}),
				    #"Added Custom" = Table.AddColumn(#"Changed Type", "Week", each Date.WeekOfYear([Date],Day.Monday))
				in
				    #"Added Custom"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

